/**
 * Univer commands that mutate workbook content, structure, or formatting.
 * Used by the edit guard to block all mutations in read-only mode.
 */
export const BLOCKED_COMMANDS: ReadonlySet<string> = new Set([
  // Cell content
  'sheet.command.set-range-values',
  'sheet.command.clear-selection-content',
  'sheet.command.clear-selection-format',
  'sheet.command.clear-selection-all',
  // Clipboard (sheet-level)
  'sheet.command.cut',
  'sheet.command.paste',
  'sheet.command.paste-value',
  'sheet.command.paste-format',
  'sheet.command.paste-col-width',
  'sheet.command.paste-besides-border',
  'sheet.command.optional-paste',
  // Clipboard (base UI / keyboard shortcuts)
  'univer.command.cut',
  'univer.command.paste',
  'sheet.command.paste-by-short-key',
  // Row operations
  'sheet.command.insert-row',
  'sheet.command.insert-row-before',
  'sheet.command.insert-row-after',
  'sheet.command.insert-row-by-range',
  'sheet.command.insert-multi-rows-above',
  'sheet.command.insert-multi-rows-after',
  'sheet.command.remove-row',
  'sheet.command.remove-row-by-range',
  'sheet.command.append-row',
  'sheet.command.move-rows',
  'sheet.command.set-row-height',
  'sheet.command.set-row-data',
  'sheet.command.delta-row-height',
  // Column operations
  'sheet.command.insert-col',
  'sheet.command.insert-col-before',
  'sheet.command.insert-col-after',
  'sheet.command.insert-col-by-range',
  'sheet.command.insert-multi-cols-before',
  'sheet.command.insert-multi-cols-right',
  'sheet.command.remove-col',
  'sheet.command.remove-col-by-range',
  'sheet.command.move-cols',
  'sheet.command.set-worksheet-col-width',
  'sheet.command.delta-column-width',
  // Range operations
  'sheet.command.delete-range-move-left',
  'sheet.command.delete-range-move-up',
  'sheet.command.delete-range-move-left-confirm',
  'sheet.command.delete-range-move-up-confirm',
  'sheet.command.insert-range-move-down',
  'sheet.command.insert-range-move-right',
  'sheet.command.insert-range-move-down-confirm',
  'sheet.command.insert-range-move-right-confirm',
  'sheet.command.move-range',
  'sheet.command.reorder-range',
  // Styling
  'sheet.command.set-style',
  'sheet.command.set-bold',
  'sheet.command.set-italic',
  'sheet.command.set-underline',
  'sheet.command.set-stroke',
  'sheet.command.set-font-family',
  'sheet.command.set-font-size',
  'sheet.command.set-text-color',
  'sheet.command.set-background-color',
  'sheet.command.set-vertical-text-align',
  'sheet.command.set-horizontal-text-align',
  'sheet.command.set-text-wrap',
  'sheet.command.set-text-rotation',
  'sheet.command.set-border',
  'sheet.command.set-border-position',
  'sheet.command.set-border-style',
  'sheet.command.set-border-color',
  'sheet.command.set-border-basic',
  // Sheet operations
  'sheet.command.insert-sheet',
  'sheet.command.remove-sheet',
  'sheet.command.remove-sheet-confirm',
  'sheet.command.set-worksheet-name',
  'sheet.command.set-worksheet-order',
  'sheet.command.set-worksheet-hidden',
  'sheet.command.copy-sheet',
  'sheet.command.set-tab-color',
  'sheet.command.set-workbook-name',
  // Merge
  'sheet.command.add-worksheet-merge',
  'sheet.command.add-worksheet-merge-all',
  'sheet.command.add-worksheet-merge-horizontal',
  'sheet.command.add-worksheet-merge-vertical',
  'sheet.command.remove-worksheet-merge',
  // Auto fill / format painter
  'sheet.command.auto-fill',
  'sheet.command.auto-clear-content',
  'sheet.command.refill',
  'sheet.command.apply-format-painter',
  // Data validation (dropdowns, checkboxes, rules)
  'sheet.command.addDataValidation',
  'sheet.command.remove-data-validation-rule',
  'sheet.command.remove-all-data-validation',
  'sheet.command.updateDataValidationRuleRange',
  'sheets.command.update-data-validation-setting',
  'sheets.command.update-data-validation-options',
  'sheets.command.clear-range-data-validation',
  'data-validation.command.addRuleAndOpen',
  'sheet.operation.show-data-validation-dropdown',
  // Drawing/image editing
  'sheet.command.delete-drawing',
  'sheet.command.remove-sheet-image',
  'sheet.command.set-sheet-image',
  'sheet.command.insert-sheet-image',
  'sheet.command.insert-float-image',
  'sheet.command.insert-cell-image',
  'sheet.command.move-drawing',
  'sheet.command.set-drawing-arrange',
  'sheet.command.group-sheet-image',
  'sheet.command.ungroup-sheet-image',
  'sheet.operation.edit-sheet-image',
  'sheet.operation.open-image-crop',
  'sheet.operation.image-reset-size',
]);
